config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_params_id, only: %i[show edit update destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save!
    redirect_to article_path(@article)
  end

  def edit
  end

  def update
    @article = Article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_params_id
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <%= simple_form_for(@article) do |f| %>
    <%= f.input :photo, as: :file %>
    <%= f.input :title %>
    <%= f.input :body %>
    <div  class="mx-auto">
      <%= f.button :submit, class: "btn btn-warning" %>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<h1>Modifier un article</h1>

<%= render 'form' , article: @article%>
<%= link_to "Nouvel article", new_article_path %>
<%= link_to "Mon article", article_path(@article) %>
<%= link_to "Mes articles", articles_path %>

app/views/articles/index.html.erb
<h1 class="text-center"> Mes Articles</h1>

<%= link_to "Nouveau", new_article_path, class: "btn btn-primary" %>
<div class="container d-flex justify-content-between">
  <% @articles.each do |article| %>
    <div class="card text-center" style="width: 18rem; margin: 8px;">
      <h5 class="card-title"><%= article.title.capitalize %></h5>
      <p><%= link_to "Lire", article_path(article), class:"btn btn-dark" %></p>
    </div>
    <%= link_to  article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-red" do %>
      "Supprimer"
    <% end %>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>Créer un article</h1>

<%= render 'form', article: @article %>
<%= link_to "Mes articles", articles_path %>

app/views/articles/show.html.erb
<div class="col-8 mx-auto my-4 card text-justify p-auto">
<h1 class="text-center"><%= @article.title.capitalize %></h1>
  <%= cl_image_tag @article.photo.key.to_s, alt: "SF", width: 600, height: 600, crop: :fill, class:"mx-auto" %>
  <p class="text-center"><%= @article.body %></p>
<%= link_to "<- Tous les articles", articles_path, class: "btn btn-dark" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codetech9Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1 class="h1 text-success">Bienvenue Sur Codetech9 Le Blog</h1>

<%= link_to "Voir les Articles", articles_path, class: "btn btn-light" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>